export interface ActivityLog {
  id: string;
  action: string;
  description: string;
  user: string;
  userId: string;
  resource: string;
  resourceId: string;
  ipAddress: string;
  userAgent: string;
  timestamp: string;
  type: 'create' | 'update' | 'delete' | 'login' | 'logout' | 'view' | 'export';
}

export const activityLogs: ActivityLog[] = [
  {
    id: '1',
    action: 'User Login',
    description: 'Successfully logged in',
    user: 'Sarah Johnson',
    userId: '1',
    resource: 'auth',
    resourceId: 'session-1',
    ipAddress: '192.168.1.100',
    userAgent: 'Chrome 120 / macOS',
    timestamp: '2024-01-15T10:30:00',
    type: 'login',
  },
  {
    id: '2',
    action: 'Project Created',
    description: 'Created new project "Customer Portal"',
    user: 'Michael Chen',
    userId: '2',
    resource: 'project',
    resourceId: '6',
    ipAddress: '192.168.1.105',
    userAgent: 'Firefox 121 / Windows',
    timestamp: '2024-01-15T10:15:00',
    type: 'create',
  },
  {
    id: '3',
    action: 'Task Updated',
    description: 'Updated task "Implement user authentication flow"',
    user: 'Sarah Johnson',
    userId: '1',
    resource: 'task',
    resourceId: '1',
    ipAddress: '192.168.1.100',
    userAgent: 'Chrome 120 / macOS',
    timestamp: '2024-01-15T09:45:00',
    type: 'update',
  },
  {
    id: '4',
    action: 'User Created',
    description: 'Created new user account for Benjamin Anderson',
    user: 'Jack Wright',
    userId: '22',
    resource: 'user',
    resourceId: '8',
    ipAddress: '192.168.1.110',
    userAgent: 'Safari 17 / macOS',
    timestamp: '2024-01-15T09:30:00',
    type: 'create',
  },
  {
    id: '5',
    action: 'Data Export',
    description: 'Exported analytics report for December 2023',
    user: 'Olivia Brown',
    userId: '5',
    resource: 'report',
    resourceId: 'report-12-2023',
    ipAddress: '192.168.1.120',
    userAgent: 'Chrome 120 / macOS',
    timestamp: '2024-01-15T09:00:00',
    type: 'export',
  },
  {
    id: '6',
    action: 'Settings Updated',
    description: 'Updated notification preferences',
    user: 'Emily Davis',
    userId: '3',
    resource: 'settings',
    resourceId: 'settings-3',
    ipAddress: '192.168.1.115',
    userAgent: 'Chrome 120 / Windows',
    timestamp: '2024-01-15T08:45:00',
    type: 'update',
  },
  {
    id: '7',
    action: 'User Logout',
    description: 'Logged out',
    user: 'William Taylor',
    userId: '6',
    resource: 'auth',
    resourceId: 'session-6',
    ipAddress: '192.168.1.125',
    userAgent: 'Edge 120 / Windows',
    timestamp: '2024-01-15T08:30:00',
    type: 'logout',
  },
  {
    id: '8',
    action: 'Team Updated',
    description: 'Added 2 new members to Platform team',
    user: 'Sarah Johnson',
    userId: '1',
    resource: 'team',
    resourceId: '1',
    ipAddress: '192.168.1.100',
    userAgent: 'Chrome 120 / macOS',
    timestamp: '2024-01-14T17:30:00',
    type: 'update',
  },
  {
    id: '9',
    action: 'Task Deleted',
    description: 'Deleted task "Old feature implementation"',
    user: 'James Wilson',
    userId: '4',
    resource: 'task',
    resourceId: 'task-old',
    ipAddress: '192.168.1.130',
    userAgent: 'Firefox 121 / Linux',
    timestamp: '2024-01-14T16:00:00',
    type: 'delete',
  },
  {
    id: '10',
    action: 'Invoice Viewed',
    description: 'Viewed invoice INV-2024-001',
    user: 'Olivia Brown',
    userId: '5',
    resource: 'invoice',
    resourceId: '1',
    ipAddress: '192.168.1.120',
    userAgent: 'Chrome 120 / macOS',
    timestamp: '2024-01-14T15:30:00',
    type: 'view',
  },
  {
    id: '11',
    action: 'API Key Generated',
    description: 'Generated new API key for production',
    user: 'Jack Wright',
    userId: '22',
    resource: 'api-key',
    resourceId: 'key-prod-1',
    ipAddress: '192.168.1.110',
    userAgent: 'Safari 17 / macOS',
    timestamp: '2024-01-14T14:00:00',
    type: 'create',
  },
  {
    id: '12',
    action: 'Subscription Updated',
    description: 'Upgraded subscription to Enterprise plan',
    user: 'Mia Rodriguez',
    userId: '11',
    resource: 'subscription',
    resourceId: '5',
    ipAddress: '192.168.1.140',
    userAgent: 'Chrome 120 / iOS',
    timestamp: '2024-01-14T11:00:00',
    type: 'update',
  },
  {
    id: '13',
    action: 'User Login',
    description: 'Successfully logged in',
    user: 'Michael Chen',
    userId: '2',
    resource: 'auth',
    resourceId: 'session-2',
    ipAddress: '192.168.1.105',
    userAgent: 'Firefox 121 / Windows',
    timestamp: '2024-01-14T09:00:00',
    type: 'login',
  },
  {
    id: '14',
    action: 'Project Updated',
    description: 'Updated project status for "Analytics Dashboard"',
    user: 'Olivia Brown',
    userId: '5',
    resource: 'project',
    resourceId: '4',
    ipAddress: '192.168.1.120',
    userAgent: 'Chrome 120 / macOS',
    timestamp: '2024-01-13T16:45:00',
    type: 'update',
  },
  {
    id: '15',
    action: 'Data Export',
    description: 'Exported user list to CSV',
    user: 'Jack Wright',
    userId: '22',
    resource: 'user',
    resourceId: 'export-users',
    ipAddress: '192.168.1.110',
    userAgent: 'Safari 17 / macOS',
    timestamp: '2024-01-13T14:30:00',
    type: 'export',
  },
];

export const getActivityLogById = (id: string) => activityLogs.find(a => a.id === id);
