export interface Project {
  id: string;
  name: string;
  description: string;
  status: 'Planning' | 'In Progress' | 'On Hold' | 'Completed' | 'Review';
  progress: number;
  team: string;
  teamId: string;
  lead: string;
  startDate: string;
  endDate: string;
  budget: number;
  spent: number;
  priority: 'Low' | 'Medium' | 'High' | 'Critical';
  tasksTotal: number;
  tasksCompleted: number;
  members: { name: string; avatar: string }[];
}

export const projects: Project[] = [
  {
    id: '1',
    name: 'Platform v2.0',
    description: 'Major platform upgrade with new architecture',
    status: 'In Progress',
    progress: 65,
    team: 'Platform',
    teamId: '1',
    lead: 'Sarah Johnson',
    startDate: '2023-06-01',
    endDate: '2024-03-31',
    budget: 500000,
    spent: 325000,
    priority: 'Critical',
    tasksTotal: 45,
    tasksCompleted: 29,
    members: [
      { name: 'Sarah Johnson', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah' },
      { name: 'Michael Chen', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael' },
    ],
  },
  {
    id: '2',
    name: 'Mobile App Redesign',
    description: 'Complete UI/UX redesign of mobile applications',
    status: 'In Progress',
    progress: 40,
    team: 'Product Design',
    teamId: '3',
    lead: 'Emily Davis',
    startDate: '2023-09-15',
    endDate: '2024-02-28',
    budget: 150000,
    spent: 60000,
    priority: 'High',
    tasksTotal: 32,
    tasksCompleted: 13,
    members: [
      { name: 'Emily Davis', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily' },
      { name: 'Isabella Thomas', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella' },
    ],
  },
  {
    id: '3',
    name: 'API Gateway',
    description: 'Centralized API gateway implementation',
    status: 'Completed',
    progress: 100,
    team: 'Backend',
    teamId: '4',
    lead: 'William Taylor',
    startDate: '2023-01-10',
    endDate: '2023-08-30',
    budget: 200000,
    spent: 185000,
    priority: 'High',
    tasksTotal: 28,
    tasksCompleted: 28,
    members: [
      { name: 'William Taylor', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=William' },
    ],
  },
  {
    id: '4',
    name: 'Analytics Dashboard',
    description: 'Real-time analytics and reporting dashboard',
    status: 'In Progress',
    progress: 78,
    team: 'Data',
    teamId: '7',
    lead: 'Olivia Brown',
    startDate: '2023-07-01',
    endDate: '2024-01-31',
    budget: 120000,
    spent: 94000,
    priority: 'Medium',
    tasksTotal: 22,
    tasksCompleted: 17,
    members: [
      { name: 'Olivia Brown', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia' },
    ],
  },
  {
    id: '5',
    name: 'CI/CD Pipeline',
    description: 'Automated deployment pipeline setup',
    status: 'In Progress',
    progress: 85,
    team: 'DevOps',
    teamId: '5',
    lead: 'Lucas Garcia',
    startDate: '2023-04-15',
    endDate: '2024-01-15',
    budget: 80000,
    spent: 68000,
    priority: 'High',
    tasksTotal: 18,
    tasksCompleted: 15,
    members: [
      { name: 'Lucas Garcia', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas' },
    ],
  },
  {
    id: '6',
    name: 'Customer Portal',
    description: 'Self-service customer portal development',
    status: 'Planning',
    progress: 10,
    team: 'Frontend',
    teamId: '2',
    lead: 'Michael Chen',
    startDate: '2024-02-01',
    endDate: '2024-06-30',
    budget: 250000,
    spent: 25000,
    priority: 'Medium',
    tasksTotal: 40,
    tasksCompleted: 4,
    members: [
      { name: 'Michael Chen', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael' },
    ],
  },
  {
    id: '7',
    name: 'Security Audit',
    description: 'Comprehensive security audit and fixes',
    status: 'On Hold',
    progress: 35,
    team: 'Security',
    teamId: '8',
    lead: 'Ethan Lee',
    startDate: '2023-10-01',
    endDate: '2024-04-30',
    budget: 100000,
    spent: 35000,
    priority: 'Critical',
    tasksTotal: 15,
    tasksCompleted: 5,
    members: [
      { name: 'Ethan Lee', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan' },
    ],
  },
  {
    id: '8',
    name: 'Mobile iOS App',
    description: 'Native iOS application development',
    status: 'In Progress',
    progress: 55,
    team: 'Mobile',
    teamId: '6',
    lead: 'Benjamin Anderson',
    startDate: '2023-08-01',
    endDate: '2024-04-30',
    budget: 180000,
    spent: 99000,
    priority: 'High',
    tasksTotal: 35,
    tasksCompleted: 19,
    members: [
      { name: 'Benjamin Anderson', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Benjamin' },
    ],
  },
  {
    id: '9',
    name: 'Brand Refresh',
    description: 'Company brand identity update',
    status: 'Completed',
    progress: 100,
    team: 'Product Design',
    teamId: '3',
    lead: 'Emily Davis',
    startDate: '2023-02-01',
    endDate: '2023-06-30',
    budget: 75000,
    spent: 72000,
    priority: 'Medium',
    tasksTotal: 20,
    tasksCompleted: 20,
    members: [
      { name: 'Emily Davis', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily' },
    ],
  },
  {
    id: '10',
    name: 'Database Migration',
    description: 'Migration to new database architecture',
    status: 'In Progress',
    progress: 30,
    team: 'Backend',
    teamId: '4',
    lead: 'William Taylor',
    startDate: '2023-11-01',
    endDate: '2024-05-31',
    budget: 150000,
    spent: 45000,
    priority: 'Critical',
    tasksTotal: 25,
    tasksCompleted: 8,
    members: [
      { name: 'William Taylor', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=William' },
      { name: 'Alexander Harris', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alexander' },
    ],
  },
];

export const getProjectById = (id: string) => projects.find(p => p.id === id);
