export interface Task {
  id: string;
  title: string;
  description: string;
  status: 'To Do' | 'In Progress' | 'Review' | 'Completed' | 'On Hold';
  priority: 'Low' | 'Medium' | 'High' | 'Critical';
  assignee: { name: string; avatar: string } | null;
  assigneeId: string;
  project: string;
  projectId: string;
  dueDate: string;
  createdAt: string;
  completedAt?: string;
  tags: string[];
}

export const tasks: Task[] = [
  {
    id: '1',
    title: 'Implement user authentication flow',
    description: 'Build complete authentication system with OAuth support',
    status: 'In Progress',
    priority: 'High',
    assignee: { name: 'Sarah Johnson', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah' },
    assigneeId: '1',
    project: 'Platform v2.0',
    projectId: '1',
    dueDate: '2024-01-20',
    createdAt: '2024-01-05',
    tags: ['backend', 'security'],
  },
  {
    id: '2',
    title: 'Design dashboard wireframes',
    description: 'Create wireframes for the new admin dashboard',
    status: 'Completed',
    priority: 'Medium',
    assignee: { name: 'Emily Davis', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily' },
    assigneeId: '3',
    project: 'Mobile App Redesign',
    projectId: '2',
    dueDate: '2024-01-15',
    createdAt: '2024-01-02',
    completedAt: '2024-01-14',
    tags: ['design', 'mobile'],
  },
  {
    id: '3',
    title: 'Set up Kubernetes cluster',
    description: 'Configure production Kubernetes cluster',
    status: 'In Progress',
    priority: 'Critical',
    assignee: { name: 'Lucas Garcia', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas' },
    assigneeId: '10',
    project: 'CI/CD Pipeline',
    projectId: '5',
    dueDate: '2024-01-18',
    createdAt: '2024-01-08',
    tags: ['devops', 'infrastructure'],
  },
  {
    id: '4',
    title: 'Write API documentation',
    description: 'Document all REST API endpoints',
    status: 'Review',
    priority: 'Medium',
    assignee: { name: 'Michael Chen', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael' },
    assigneeId: '2',
    project: 'API Gateway',
    projectId: '3',
    dueDate: '2024-01-22',
    createdAt: '2024-01-10',
    tags: ['documentation', 'api'],
  },
  {
    id: '5',
    title: 'Fix payment gateway bug',
    description: 'Resolve payment processing timeout issues',
    status: 'In Progress',
    priority: 'Critical',
    assignee: { name: 'William Taylor', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=William' },
    assigneeId: '6',
    project: 'Platform v2.0',
    projectId: '1',
    dueDate: '2024-01-16',
    createdAt: '2024-01-12',
    tags: ['bug', 'payments'],
  },
  {
    id: '6',
    title: 'Create onboarding flow',
    description: 'Design and implement user onboarding experience',
    status: 'To Do',
    priority: 'High',
    assignee: { name: 'Isabella Thomas', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella' },
    assigneeId: '9',
    project: 'Mobile App Redesign',
    projectId: '2',
    dueDate: '2024-01-28',
    createdAt: '2024-01-13',
    tags: ['design', 'ux'],
  },
  {
    id: '7',
    title: 'Performance optimization',
    description: 'Optimize database queries and caching',
    status: 'In Progress',
    priority: 'High',
    assignee: { name: 'Alexander Harris', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alexander' },
    assigneeId: '14',
    project: 'Analytics Dashboard',
    projectId: '4',
    dueDate: '2024-01-25',
    createdAt: '2024-01-09',
    tags: ['performance', 'database'],
  },
  {
    id: '8',
    title: 'Security vulnerability scan',
    description: 'Run comprehensive security scan on all services',
    status: 'To Do',
    priority: 'Critical',
    assignee: { name: 'Ethan Lee', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan' },
    assigneeId: '12',
    project: 'Security Audit',
    projectId: '7',
    dueDate: '2024-01-19',
    createdAt: '2024-01-11',
    tags: ['security', 'audit'],
  },
  {
    id: '9',
    title: 'Mobile push notifications',
    description: 'Implement push notification system for mobile apps',
    status: 'In Progress',
    priority: 'Medium',
    assignee: { name: 'Benjamin Anderson', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Benjamin' },
    assigneeId: '8',
    project: 'Mobile iOS App',
    projectId: '8',
    dueDate: '2024-01-30',
    createdAt: '2024-01-06',
    tags: ['mobile', 'notifications'],
  },
  {
    id: '10',
    title: 'Update brand guidelines',
    description: 'Create comprehensive brand guidelines document',
    status: 'Completed',
    priority: 'Low',
    assignee: { name: 'Grace King', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Grace' },
    assigneeId: '21',
    project: 'Brand Refresh',
    projectId: '9',
    dueDate: '2024-01-12',
    createdAt: '2024-01-03',
    completedAt: '2024-01-11',
    tags: ['design', 'branding'],
  },
  {
    id: '11',
    title: 'Database schema migration',
    description: 'Migrate legacy schema to new normalized structure',
    status: 'To Do',
    priority: 'High',
    assignee: { name: 'Daniel Walker', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel' },
    assigneeId: '18',
    project: 'Database Migration',
    projectId: '10',
    dueDate: '2024-02-05',
    createdAt: '2024-01-14',
    tags: ['database', 'migration'],
  },
  {
    id: '12',
    title: 'Unit test coverage',
    description: 'Increase unit test coverage to 80%',
    status: 'In Progress',
    priority: 'Medium',
    assignee: { name: 'Michael Chen', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael' },
    assigneeId: '2',
    project: 'Platform v2.0',
    projectId: '1',
    dueDate: '2024-01-31',
    createdAt: '2024-01-07',
    tags: ['testing', 'quality'],
  },
  {
    id: '13',
    title: 'Customer feedback analysis',
    description: 'Analyze and categorize customer feedback data',
    status: 'Completed',
    priority: 'Medium',
    assignee: { name: 'Olivia Brown', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia' },
    assigneeId: '5',
    project: 'Analytics Dashboard',
    projectId: '4',
    dueDate: '2024-01-10',
    createdAt: '2024-01-04',
    completedAt: '2024-01-09',
    tags: ['analytics', 'feedback'],
  },
  {
    id: '14',
    title: 'API rate limiting',
    description: 'Implement rate limiting for API endpoints',
    status: 'Review',
    priority: 'High',
    assignee: { name: 'William Taylor', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=William' },
    assigneeId: '6',
    project: 'API Gateway',
    projectId: '3',
    dueDate: '2024-01-17',
    createdAt: '2024-01-08',
    tags: ['api', 'security'],
  },
  {
    id: '15',
    title: 'User interface components',
    description: 'Build reusable UI component library',
    status: 'In Progress',
    priority: 'Medium',
    assignee: { name: 'Charlotte Clark', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlotte' },
    assigneeId: '15',
    project: 'Customer Portal',
    projectId: '6',
    dueDate: '2024-02-15',
    createdAt: '2024-01-10',
    tags: ['frontend', 'components'],
  },
  {
    id: '16',
    title: 'Load testing',
    description: 'Perform load testing on production systems',
    status: 'To Do',
    priority: 'High',
    assignee: { name: 'Lucas Garcia', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas' },
    assigneeId: '10',
    project: 'CI/CD Pipeline',
    projectId: '5',
    dueDate: '2024-01-23',
    createdAt: '2024-01-12',
    tags: ['testing', 'performance'],
  },
  {
    id: '17',
    title: 'Error tracking setup',
    description: 'Set up error tracking and monitoring',
    status: 'Completed',
    priority: 'Medium',
    assignee: { name: 'Sebastian Young', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sebastian' },
    assigneeId: '20',
    project: 'Platform v2.0',
    projectId: '1',
    dueDate: '2024-01-08',
    createdAt: '2024-01-02',
    completedAt: '2024-01-07',
    tags: ['monitoring', 'devops'],
  },
  {
    id: '18',
    title: 'Accessibility audit',
    description: 'Conduct accessibility compliance audit',
    status: 'To Do',
    priority: 'Medium',
    assignee: { name: 'Emily Davis', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily' },
    assigneeId: '3',
    project: 'Mobile App Redesign',
    projectId: '2',
    dueDate: '2024-02-01',
    createdAt: '2024-01-14',
    tags: ['accessibility', 'compliance'],
  },
  {
    id: '19',
    title: 'Data backup automation',
    description: 'Automate database backup procedures',
    status: 'In Progress',
    priority: 'High',
    assignee: { name: 'Alexander Harris', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alexander' },
    assigneeId: '14',
    project: 'Database Migration',
    projectId: '10',
    dueDate: '2024-01-26',
    createdAt: '2024-01-09',
    tags: ['database', 'automation'],
  },
  {
    id: '20',
    title: 'Customer support training',
    description: 'Prepare training materials for support team',
    status: 'To Do',
    priority: 'Low',
    assignee: { name: 'Henry Lewis', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Henry' },
    assigneeId: '16',
    project: 'Customer Portal',
    projectId: '6',
    dueDate: '2024-02-10',
    createdAt: '2024-01-13',
    tags: ['training', 'support'],
  },
];

export const getTaskById = (id: string) => tasks.find(t => t.id === id);
