export interface User {
  id: string;
  name: string;
  email: string;
  avatar: string;
  role: 'Admin' | 'Manager' | 'Developer' | 'Designer' | 'Analyst' | 'Support';
  status: 'Active' | 'Inactive' | 'Pending' | 'Suspended';
  department: string;
  joinDate: string;
  lastActive: string;
  location: string;
  phone: string;
  team: string;
}

export const users: User[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    role: 'Admin',
    status: 'Active',
    department: 'Engineering',
    joinDate: '2022-01-15',
    lastActive: '2024-01-15T10:30:00',
    location: 'San Francisco, CA',
    phone: '+1 (555) 123-4567',
    team: 'Platform',
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    role: 'Developer',
    status: 'Active',
    department: 'Engineering',
    joinDate: '2022-03-20',
    lastActive: '2024-01-15T09:15:00',
    location: 'New York, NY',
    phone: '+1 (555) 234-5678',
    team: 'Frontend',
  },
  {
    id: '3',
    name: 'Emily Davis',
    email: 'emily.davis@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    role: 'Designer',
    status: 'Active',
    department: 'Design',
    joinDate: '2022-05-10',
    lastActive: '2024-01-14T16:45:00',
    location: 'Los Angeles, CA',
    phone: '+1 (555) 345-6789',
    team: 'Product Design',
  },
  {
    id: '4',
    name: 'James Wilson',
    email: 'james.wilson@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    role: 'Manager',
    status: 'Active',
    department: 'Product',
    joinDate: '2021-11-08',
    lastActive: '2024-01-15T11:00:00',
    location: 'Chicago, IL',
    phone: '+1 (555) 456-7890',
    team: 'Product',
  },
  {
    id: '5',
    name: 'Olivia Brown',
    email: 'olivia.brown@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia',
    role: 'Analyst',
    status: 'Active',
    department: 'Analytics',
    joinDate: '2023-02-28',
    lastActive: '2024-01-15T08:30:00',
    location: 'Boston, MA',
    phone: '+1 (555) 567-8901',
    team: 'Data',
  },
  {
    id: '6',
    name: 'William Taylor',
    email: 'william.taylor@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=William',
    role: 'Developer',
    status: 'Inactive',
    department: 'Engineering',
    joinDate: '2022-07-14',
    lastActive: '2024-01-10T14:20:00',
    location: 'Seattle, WA',
    phone: '+1 (555) 678-9012',
    team: 'Backend',
  },
  {
    id: '7',
    name: 'Sophia Martinez',
    email: 'sophia.martinez@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia',
    role: 'Support',
    status: 'Active',
    department: 'Customer Success',
    joinDate: '2023-05-22',
    lastActive: '2024-01-15T10:00:00',
    location: 'Austin, TX',
    phone: '+1 (555) 789-0123',
    team: 'Support',
  },
  {
    id: '8',
    name: 'Benjamin Anderson',
    email: 'benjamin.anderson@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Benjamin',
    role: 'Developer',
    status: 'Pending',
    department: 'Engineering',
    joinDate: '2024-01-10',
    lastActive: '2024-01-14T09:00:00',
    location: 'Denver, CO',
    phone: '+1 (555) 890-1234',
    team: 'Mobile',
  },
  {
    id: '9',
    name: 'Isabella Thomas',
    email: 'isabella.thomas@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    role: 'Designer',
    status: 'Active',
    department: 'Design',
    joinDate: '2023-08-15',
    lastActive: '2024-01-15T07:45:00',
    location: 'Miami, FL',
    phone: '+1 (555) 901-2345',
    team: 'Brand',
  },
  {
    id: '10',
    name: 'Lucas Garcia',
    email: 'lucas.garcia@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas',
    role: 'Developer',
    status: 'Active',
    department: 'Engineering',
    joinDate: '2022-09-01',
    lastActive: '2024-01-15T11:30:00',
    location: 'Portland, OR',
    phone: '+1 (555) 012-3456',
    team: 'DevOps',
  },
  {
    id: '11',
    name: 'Mia Rodriguez',
    email: 'mia.rodriguez@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mia',
    role: 'Manager',
    status: 'Active',
    department: 'Marketing',
    joinDate: '2021-12-01',
    lastActive: '2024-01-15T09:30:00',
    location: 'Phoenix, AZ',
    phone: '+1 (555) 123-4568',
    team: 'Marketing',
  },
  {
    id: '12',
    name: 'Ethan Lee',
    email: 'ethan.lee@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan',
    role: 'Developer',
    status: 'Suspended',
    department: 'Engineering',
    joinDate: '2023-01-15',
    lastActive: '2024-01-05T16:00:00',
    location: 'Dallas, TX',
    phone: '+1 (555) 234-5679',
    team: 'Security',
  },
  {
    id: '13',
    name: 'Ava White',
    email: 'ava.white@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ava',
    role: 'Analyst',
    status: 'Active',
    department: 'Finance',
    joinDate: '2022-04-18',
    lastActive: '2024-01-15T10:15:00',
    location: 'Atlanta, GA',
    phone: '+1 (555) 345-6780',
    team: 'Finance',
  },
  {
    id: '14',
    name: 'Alexander Harris',
    email: 'alexander.harris@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alexander',
    role: 'Developer',
    status: 'Active',
    department: 'Engineering',
    joinDate: '2023-06-01',
    lastActive: '2024-01-15T08:00:00',
    location: 'San Diego, CA',
    phone: '+1 (555) 456-7891',
    team: 'Platform',
  },
  {
    id: '15',
    name: 'Charlotte Clark',
    email: 'charlotte.clark@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlotte',
    role: 'Designer',
    status: 'Active',
    department: 'Design',
    joinDate: '2022-11-20',
    lastActive: '2024-01-14T17:30:00',
    location: 'Nashville, TN',
    phone: '+1 (555) 567-8902',
    team: 'UX Research',
  },
  {
    id: '16',
    name: 'Henry Lewis',
    email: 'henry.lewis@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Henry',
    role: 'Support',
    status: 'Active',
    department: 'Customer Success',
    joinDate: '2023-09-10',
    lastActive: '2024-01-15T11:45:00',
    location: 'Minneapolis, MN',
    phone: '+1 (555) 678-9013',
    team: 'Enterprise',
  },
  {
    id: '17',
    name: 'Amelia Robinson',
    email: 'amelia.robinson@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amelia',
    role: 'Manager',
    status: 'Active',
    department: 'Operations',
    joinDate: '2021-09-05',
    lastActive: '2024-01-15T09:00:00',
    location: 'Detroit, MI',
    phone: '+1 (555) 789-0124',
    team: 'Operations',
  },
  {
    id: '18',
    name: 'Daniel Walker',
    email: 'daniel.walker@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel',
    role: 'Developer',
    status: 'Active',
    department: 'Engineering',
    joinDate: '2023-03-25',
    lastActive: '2024-01-15T10:00:00',
    location: 'Tampa, FL',
    phone: '+1 (555) 890-1235',
    team: 'Frontend',
  },
  {
    id: '19',
    name: 'Victoria Hall',
    email: 'victoria.hall@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Victoria',
    role: 'Analyst',
    status: 'Inactive',
    department: 'Analytics',
    joinDate: '2022-08-12',
    lastActive: '2024-01-08T15:30:00',
    location: 'Baltimore, MD',
    phone: '+1 (555) 901-2346',
    team: 'Business',
  },
  {
    id: '20',
    name: 'Sebastian Young',
    email: 'sebastian.young@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sebastian',
    role: 'Developer',
    status: 'Active',
    department: 'Engineering',
    joinDate: '2023-07-18',
    lastActive: '2024-01-15T08:30:00',
    location: 'Cleveland, OH',
    phone: '+1 (555) 012-3457',
    team: 'Backend',
  },
  {
    id: '21',
    name: 'Grace King',
    email: 'grace.king@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Grace',
    role: 'Designer',
    status: 'Active',
    department: 'Design',
    joinDate: '2023-10-05',
    lastActive: '2024-01-15T09:45:00',
    location: 'St. Louis, MO',
    phone: '+1 (555) 123-4569',
    team: 'Product Design',
  },
  {
    id: '22',
    name: 'Jack Wright',
    email: 'jack.wright@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jack',
    role: 'Admin',
    status: 'Active',
    department: 'IT',
    joinDate: '2021-05-20',
    lastActive: '2024-01-15T07:00:00',
    location: 'Pittsburgh, PA',
    phone: '+1 (555) 234-5680',
    team: 'IT',
  },
];

export const getUserById = (id: string) => users.find(u => u.id === id);
